# Generated by Django 6.0.7 on 2026-09-08 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_remove_orderitem_order_remove_orderitem_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_featured_in_hero',
            field=models.BooleanField(default=False, help_text="Show this category's newest in-stock product as an auto-rotating homepage announcement slide."),
        ),
    ]
