# Generated by Django 6.0.7 on 2026-09-09 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_category_is_featured_in_hero'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, help_text='Public support email shown on the Contact page.', max_length=254)),
                ('phone_number', models.CharField(blank=True, help_text='Phone number for calls/SMS, e.g. +996700123456', max_length=32)),
                ('whatsapp_number', models.CharField(blank=True, help_text='WhatsApp number with country code, digits only, e.g. 996700123456', max_length=32)),
                ('telegram_username', models.CharField(blank=True, help_text='Telegram username without the @, e.g. techvault_support', max_length=100)),
                ('instagram_username', models.CharField(blank=True, help_text='Instagram username without the @, e.g. techvault.shop', max_length=100)),
            ],
            options={
                'verbose_name': 'Contact Settings',
                'verbose_name_plural': 'Contact Settings',
            },
        ),
    ]
