# Generated by Django 6.0.7 on 2026-09-09 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_contactsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_text', models.CharField(blank=True, default='Enterprise Architecture', help_text="Small pill label above the page heading, e.g. 'Family Owned Since 2010'.", max_length=100)),
                ('heading', models.CharField(default='About TechVault', max_length=150)),
                ('intro_text', models.TextField(default='TechVault is an online showcase for the phones, laptops, and tablets we carry. Browse the full catalog, compare specifications, and find your next device before you visit us.', help_text='The main story paragraph under the heading. Write about your shop, your market, and what makes you different.')),
                ('visit_heading', models.CharField(blank=True, default='See It In Person', max_length=150)),
                ('visit_text', models.TextField(blank=True, default='This catalog is for browsing: use it to compare specifications and shortlist the devices you like, then stop by our store to see them up close and speak with our team.')),
                ('store_address_line1', models.CharField(blank=True, default='100 Tech Vault Plaza, Suite 404', max_length=200)),
                ('store_address_line2', models.CharField(blank=True, default='Silicon District, CA 94016', max_length=200)),
                ('store_image', models.ImageField(blank=True, help_text='Optional photo of your storefront. Falls back to a generic map graphic if left empty.', null=True, upload_to='about/')),
                ('cta_heading', models.CharField(blank=True, default='Ready to Find Your Next Device?', max_length=150)),
                ('cta_text', models.TextField(blank=True, default='Browse our full catalog of phones, laptops, and tablets, then visit us in-store or get in touch to learn more.')),
            ],
            options={
                'verbose_name': 'About Page Content',
                'verbose_name_plural': 'About Page Content',
            },
        ),
    ]
