# Generated by Django 6.0.7 on 2026-09-09 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_aboutpagecontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='show_newest_row',
            field=models.BooleanField(default=True, help_text='Show this category\'s own "Newest In" slideshow row on the homepage.'),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='shop.product')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
