# Generated by Django 6.0.7 on 2026-09-09 18:49

from django.db import migrations, models


def backfill_category_numbers(apps, schema_editor):
    """
    Every existing product currently got category_number=0 from the field's
    default when the column was added. Before the uniqueness constraint below
    is enforced, give each product a unique, sequential number within its own
    category (oldest product first), so categories with more than one
    existing product don't collide on 0.
    """
    Product = apps.get_model('shop', 'Product')
    Category = apps.get_model('shop', 'Category')
    for category in Category.objects.all():
        products = Product.objects.filter(category=category).order_by('created_at', 'id')
        for index, product in enumerate(products):
            if product.category_number != index:
                product.category_number = index
                product.save(update_fields=['category_number'])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_category_show_newest_row_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpagecontent',
            name='site_name',
            field=models.CharField(default='TechVault', help_text='The store/market name shown in the navbar, browser tab, and footer across the whole site.', max_length=60),
        ),
        migrations.AddField(
            model_name='product',
            name='category_number',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.RunPython(backfill_category_numbers, noop_reverse),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('category', 'category_number'), name='unique_category_number_per_category'),
        ),
    ]
