# Generated by Django 6.0.7 on 2026-09-09 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_aboutpagecontent_site_name_product_category_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpagecontent',
            name='badge_text_ky',
            field=models.CharField(blank=True, max_length=100, verbose_name='Badge Text (Kyrgyz)'),
        ),
        migrations.AddField(
            model_name='aboutpagecontent',
            name='badge_text_ru',
            field=models.CharField(blank=True, max_length=100, verbose_name='Badge Text (Russian)'),
        ),
        migrations.AddField(
            model_name='aboutpagecontent',
            name='cta_heading_ky',
            field=models.CharField(blank=True, max_length=150, verbose_name='Banner Heading (Kyrgyz)'),
        ),
        migrations.AddField(
            model_name='aboutpagecontent',
            name='cta_heading_ru',
            field=models.CharField(blank=True, max_length=150, verbose_name='Banner Heading (Russian)'),
        ),
        migrations.AddField(
            model_name='aboutpagecontent',
            name='cta_text_ky',
            field=models.TextField(blank=True, verbose_name='Banner Text (Kyrgyz)'),
        ),
        migrations.AddField(
            model_name='aboutpagecontent',
            name='cta_text_ru',
            field=models.TextField(blank=True, verbose_name='Banner Text (Russian)'),
        ),
        migrations.AddField(
            model_name='aboutpagecontent',
            name='heading_ky',
            field=models.CharField(blank=True, max_length=150, verbose_name='Page Heading (Kyrgyz)'),
        ),
        migrations.AddField(
            model_name='aboutpagecontent',
            name='heading_ru',
            field=models.CharField(blank=True, max_length=150, verbose_name='Page Heading (Russian)'),
        ),
        migrations.AddField(
            model_name='aboutpagecontent',
            name='intro_text_ky',
            field=models.TextField(blank=True, verbose_name='Your Story (Kyrgyz)'),
        ),
        migrations.AddField(
            model_name='aboutpagecontent',
            name='intro_text_ru',
            field=models.TextField(blank=True, verbose_name='Your Story (Russian)'),
        ),
        migrations.AddField(
            model_name='aboutpagecontent',
            name='site_name_ky',
            field=models.CharField(blank=True, max_length=60, verbose_name='Store / Market Name (Kyrgyz)'),
        ),
        migrations.AddField(
            model_name='aboutpagecontent',
            name='site_name_ru',
            field=models.CharField(blank=True, max_length=60, verbose_name='Store / Market Name (Russian)'),
        ),
        migrations.AddField(
            model_name='aboutpagecontent',
            name='store_address_line1_ky',
            field=models.CharField(blank=True, max_length=200, verbose_name='Address Line 1 (Kyrgyz)'),
        ),
        migrations.AddField(
            model_name='aboutpagecontent',
            name='store_address_line1_ru',
            field=models.CharField(blank=True, max_length=200, verbose_name='Address Line 1 (Russian)'),
        ),
        migrations.AddField(
            model_name='aboutpagecontent',
            name='store_address_line2_ky',
            field=models.CharField(blank=True, max_length=200, verbose_name='Address Line 2 (Kyrgyz)'),
        ),
        migrations.AddField(
            model_name='aboutpagecontent',
            name='store_address_line2_ru',
            field=models.CharField(blank=True, max_length=200, verbose_name='Address Line 2 (Russian)'),
        ),
        migrations.AddField(
            model_name='aboutpagecontent',
            name='visit_heading_ky',
            field=models.CharField(blank=True, max_length=150, verbose_name='Visit Section Heading (Kyrgyz)'),
        ),
        migrations.AddField(
            model_name='aboutpagecontent',
            name='visit_heading_ru',
            field=models.CharField(blank=True, max_length=150, verbose_name='Visit Section Heading (Russian)'),
        ),
        migrations.AddField(
            model_name='aboutpagecontent',
            name='visit_text_ky',
            field=models.TextField(blank=True, verbose_name='Visit Section Text (Kyrgyz)'),
        ),
        migrations.AddField(
            model_name='aboutpagecontent',
            name='visit_text_ru',
            field=models.TextField(blank=True, verbose_name='Visit Section Text (Russian)'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ky',
            field=models.CharField(blank=True, max_length=100, verbose_name='Name (Kyrgyz)'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(blank=True, max_length=100, verbose_name='Name (Russian)'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ky',
            field=models.TextField(blank=True, verbose_name='Product Description (Kyrgyz)'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ru',
            field=models.TextField(blank=True, verbose_name='Product Description (Russian)'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ky',
            field=models.CharField(blank=True, max_length=255, verbose_name='Product Title (Kyrgyz)'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ru',
            field=models.CharField(blank=True, max_length=255, verbose_name='Product Title (Russian)'),
        ),
    ]
