# Generated by Django 6.0.7 on 2026-09-15 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_aboutpagecontent_badge_text_ky_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('category_name', models.CharField(blank=True, max_length=100)),
                ('catalog_code', models.CharField(blank=True, max_length=50)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price at the moment of the sale.', max_digits=10)),
                ('sold_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('product', models.ForeignKey(blank=True, help_text='The catalog listing this sale came from, if it still exists.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='shop.product')),
                ('sold_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_sales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sold_at'],
                'indexes': [models.Index(fields=['sold_at'], name='shop_sale_sold_at_cdc127_idx')],
            },
        ),
    ]
