"""Catalog seed data: 8 categories, ~60 gadgets, prices in som.

Every category lists the slugs it may already exist under (a live store
had "Наушники" as `naushniki` before this seed existed) so seeding never
creates a second headphones category. Product names deliberately leave
the brand out — the card shows brand and name as separate lines.
"""

CATEGORIES = [
    {
        'key': 'phones', 'slugs': ['mobile-phones', 'phones', 'smartphones'],
        'name': 'Mobile Phone', 'name_ru': 'Смартфоны', 'name_ky': 'Смартфондор',
        'shape': 'phone', 'accent': '#3557e8', 'hero': True,
    },
    {
        'key': 'laptops', 'slugs': ['laptops', 'laptop', 'notebooks'],
        'name': 'Laptop', 'name_ru': 'Ноутбуки', 'name_ky': 'Ноутбуктар',
        'shape': 'laptop', 'accent': '#0e7490', 'hero': True,
    },
    {
        'key': 'tablets', 'slugs': ['tablet', 'tablets'],
        'name': 'Tablet', 'name_ru': 'Планшеты', 'name_ky': 'Планшеттер',
        'shape': 'tablet', 'accent': '#047857', 'hero': True,
    },
    {
        'key': 'headphones', 'slugs': ['headphones', 'naushniki', 'earphones'],
        'name': 'Headphones', 'name_ru': 'Наушники', 'name_ky': 'Кулакчындар',
        'shape': 'headphones', 'accent': '#7e22ce', 'hero': False,
    },
    {
        'key': 'watches', 'slugs': ['smartwatches', 'smart-watches', 'watches', 'umnye-chasy'],
        'name': 'Smartwatch', 'name_ru': 'Умные часы', 'name_ky': 'Акылдуу сааттар',
        'shape': 'watch', 'accent': '#b45309', 'hero': False,
    },
    {
        'key': 'monitors', 'slugs': ['monitors', 'monitory', 'monitor'],
        'name': 'Monitor', 'name_ru': 'Мониторы', 'name_ky': 'Мониторлор',
        'shape': 'monitor', 'accent': '#be123c', 'hero': False,
    },
    {
        'key': 'speakers', 'slugs': ['speakers', 'kolonki', 'bluetooth-speakers'],
        'name': 'Speaker', 'name_ru': 'Колонки', 'name_ky': 'Колонкалар',
        'shape': 'speaker', 'accent': '#0369a1', 'hero': False,
    },
    {
        'key': 'accessories', 'slugs': ['accessories', 'aksessuary'],
        'name': 'Accessories', 'name_ru': 'Аксессуары', 'name_ky': 'Аксессуарлар',
        'shape': 'powerbank', 'accent': '#0f766e', 'hero': False,
    },
]


def _p(category, brand, name, price, description, description_ru, shape=None, **specs):
    return {
        'category': category, 'brand': brand, 'name': name, 'price': price,
        'description': description, 'description_ru': description_ru,
        'specifications': specs, 'shape': shape,  # None: the category's shape
    }


PRODUCTS = [
    # ---- Phones -----------------------------------------------------------
    _p('phones', 'Apple', 'iPhone 16 Pro', 109900,
       'Titanium design with the A18 Pro chip, a 6.3-inch ProMotion display and a 48MP Fusion camera system.',
       'Титановый корпус, чип A18 Pro, дисплей ProMotion 6,3 дюйма и камера 48 МП Fusion.',
       Chipset='A18 Pro', Storage='256GB', Screen='6.3 inch OLED 120Hz', Camera='48MP'),
    _p('phones', 'Apple', 'iPhone 15', 74900,
       'Dynamic Island, a 48MP main camera and USB-C in a colour-infused glass and aluminium design.',
       'Dynamic Island, основная камера 48 МП и USB-C в корпусе из цветного стекла и алюминия.',
       Chipset='A16 Bionic', Storage='128GB', Screen='6.1 inch OLED', Camera='48MP'),
    _p('phones', 'Samsung', 'Galaxy S24 Ultra', 114900,
       'Galaxy AI, built-in S Pen and a 200MP camera on a 6.8-inch QHD+ display with titanium frame.',
       'Galaxy AI, встроенный S Pen и камера 200 МП на 6,8-дюймовом дисплее QHD+ в титановой рамке.',
       Chipset='Snapdragon 8 Gen 3', RAM='12GB', Storage='256GB', Screen='6.8 inch QHD+ 120Hz'),
    _p('phones', 'Samsung', 'Galaxy A55', 36900,
       'Super AMOLED 120Hz display, a metal frame and a 50MP OIS camera at a mid-range price.',
       'Дисплей Super AMOLED 120 Гц, металлическая рамка и камера 50 МП с OIS по средней цене.',
       Chipset='Exynos 1480', RAM='8GB', Storage='256GB', Screen='6.6 inch AMOLED 120Hz'),
    _p('phones', 'Xiaomi', 'Xiaomi 14', 64900,
       'Compact flagship with a Leica triple camera, Snapdragon 8 Gen 3 and 90W wired charging.',
       'Компактный флагман с тройной камерой Leica, Snapdragon 8 Gen 3 и зарядкой 90 Вт.',
       Chipset='Snapdragon 8 Gen 3', RAM='12GB', Storage='256GB', Screen='6.36 inch AMOLED 120Hz'),
    _p('phones', 'Xiaomi', 'Redmi Note 13 Pro', 24900,
       '200MP camera and a 6.67-inch AMOLED display with 67W fast charging.',
       'Камера 200 МП и AMOLED-дисплей 6,67 дюйма с быстрой зарядкой 67 Вт.',
       Chipset='Helio G99-Ultra', RAM='8GB', Storage='256GB', Camera='200MP'),
    _p('phones', 'Google', 'Pixel 8a', 44900,
       'Google Tensor G3, seven years of updates and the best point-and-shoot camera in its class.',
       'Google Tensor G3, семь лет обновлений и лучшая камера в своём классе.',
       Chipset='Tensor G3', RAM='8GB', Storage='128GB', Screen='6.1 inch OLED 120Hz'),
    _p('phones', 'Honor', 'Magic6 Lite', 27900,
       'Drop-resistant 6.78-inch curved display and a 5300mAh battery that lasts two days.',
       'Ударопрочный изогнутый дисплей 6,78 дюйма и батарея 5300 мАч на два дня.',
       Chipset='Snapdragon 6 Gen 1', RAM='8GB', Storage='256GB', Battery='5300mAh'),

    # ---- Laptops ----------------------------------------------------------
    _p('laptops', 'Apple', 'MacBook Air 13 M3', 109900,
       'Fanless, 1.24 kg, up to 18 hours of battery life and the M3 chip in a 13.6-inch Liquid Retina display.',
       'Без вентилятора, 1,24 кг, до 18 часов работы и чип M3 с 13,6-дюймовым дисплеем Liquid Retina.',
       CPU='Apple M3', RAM='8GB', Storage='256GB SSD', Screen='13.6 inch Liquid Retina'),
    _p('laptops', 'Apple', 'MacBook Pro 14 M3 Pro', 189900,
       'M3 Pro power with a 14.2-inch Liquid Retina XDR display, three Thunderbolt 4 ports and HDMI.',
       'Мощь M3 Pro, 14,2-дюймовый дисплей Liquid Retina XDR, три порта Thunderbolt 4 и HDMI.',
       CPU='Apple M3 Pro', RAM='18GB', Storage='512GB SSD', Screen='14.2 inch XDR 120Hz'),
    _p('laptops', 'Lenovo', 'IdeaPad Slim 5', 62900,
       'Thin all-metal 16-inch laptop with Ryzen 7 and a bright WUXGA display for work and study.',
       'Тонкий цельнометаллический 16-дюймовый ноутбук с Ryzen 7 и ярким дисплеем WUXGA для работы и учёбы.',
       CPU='Ryzen 7 7730U', RAM='16GB', Storage='512GB SSD', Screen='16 inch WUXGA IPS'),
    _p('laptops', 'Lenovo', 'Legion 5', 129900,
       'Gaming laptop with RTX 4060, a 165Hz display and Legion Coldfront cooling.',
       'Игровой ноутбук с RTX 4060, дисплеем 165 Гц и системой охлаждения Legion Coldfront.',
       CPU='Ryzen 7 7745HX', GPU='RTX 4060 8GB', RAM='16GB', Storage='1TB SSD', Screen='16 inch 165Hz'),
    _p('laptops', 'ASUS', 'Vivobook 15', 44900,
       'Everyday 15.6-inch laptop with a 13th-gen Core i5, backlit keyboard and fingerprint login.',
       'Ноутбук 15,6 дюйма на каждый день с Core i5 13-го поколения, подсветкой клавиатуры и сканером отпечатка.',
       CPU='Core i5-1335U', RAM='8GB', Storage='512GB SSD', Screen='15.6 inch FHD'),
    _p('laptops', 'ASUS', 'ROG Strix G16', 149900,
       'Core i7 HX and RTX 4070 behind a 16-inch 165Hz display with full RGB lighting.',
       'Core i7 HX и RTX 4070 с 16-дюймовым дисплеем 165 Гц и полной RGB-подсветкой.',
       CPU='Core i7-13650HX', GPU='RTX 4070 8GB', RAM='16GB', Storage='1TB SSD', Screen='16 inch 165Hz'),
    _p('laptops', 'HP', 'Pavilion 15', 54900,
       'Balanced Ryzen 5 laptop with 16GB of RAM, a FHD IPS panel and fast charge to 50% in 45 minutes.',
       'Сбалансированный ноутбук на Ryzen 5 с 16 ГБ ОЗУ, IPS-панелью FHD и быстрой зарядкой до 50% за 45 минут.',
       CPU='Ryzen 5 7530U', RAM='16GB', Storage='512GB SSD', Screen='15.6 inch FHD IPS'),
    _p('laptops', 'Acer', 'Aspire 5', 49900,
       'Slim aluminium-top laptop with Core i5, Wi-Fi 6 and an upgradeable SSD slot.',
       'Тонкий ноутбук с алюминиевой крышкой, Core i5, Wi-Fi 6 и свободным слотом под SSD.',
       CPU='Core i5-1235U', RAM='16GB', Storage='512GB SSD', Screen='15.6 inch FHD'),
    _p('laptops', 'Dell', 'XPS 13', 139900,
       'Premium 13.4-inch ultrabook with a 3K OLED display, Core Ultra 7 and a machined aluminium chassis.',
       'Премиальный 13,4-дюймовый ультрабук с 3K OLED-дисплеем, Core Ultra 7 и фрезерованным алюминиевым корпусом.',
       CPU='Core Ultra 7', RAM='16GB', Storage='512GB SSD', Screen='13.4 inch 3K OLED'),

    # ---- Tablets ----------------------------------------------------------
    _p('tablets', 'Apple', 'iPad 10th Gen', 42900,
       'All-screen 10.9-inch iPad with the A14 Bionic, USB-C and a landscape front camera.',
       'Безрамочный iPad 10,9 дюйма с A14 Bionic, USB-C и фронтальной камерой в альбомной ориентации.',
       Chipset='A14 Bionic', Storage='64GB', Screen='10.9 inch Liquid Retina', Connectivity='Wi-Fi'),
    _p('tablets', 'Apple', 'iPad Air 11 M2', 64900,
       'M2 performance, Apple Pencil Pro support and a 12MP landscape camera in a thin 11-inch body.',
       'Производительность M2, поддержка Apple Pencil Pro и камера 12 МП в тонком 11-дюймовом корпусе.',
       Chipset='Apple M2', Storage='128GB', Screen='11 inch Liquid Retina', Connectivity='Wi-Fi'),
    _p('tablets', 'Apple', 'iPad Pro 11 M4', 109900,
       'The thinnest Apple product ever: M4 chip, tandem OLED Ultra Retina XDR and 5.3mm thickness.',
       'Самое тонкое устройство Apple: чип M4, OLED-дисплей Ultra Retina XDR и толщина 5,3 мм.',
       Chipset='Apple M4', Storage='256GB', Screen='11 inch OLED 120Hz', Connectivity='Wi-Fi'),
    _p('tablets', 'Samsung', 'Galaxy Tab S9 FE', 44900,
       'IP68 water-resistant tablet with an included S Pen and a 10.9-inch 90Hz display.',
       'Планшет с защитой IP68, S Pen в комплекте и 10,9-дюймовым дисплеем 90 Гц.',
       Chipset='Exynos 1380', RAM='6GB', Storage='128GB', Screen='10.9 inch 90Hz'),
    _p('tablets', 'Samsung', 'Galaxy Tab A9+', 21900,
       'Affordable 11-inch tablet with quad speakers and a 90Hz screen for streaming and reading.',
       'Доступный 11-дюймовый планшет с четырьмя динамиками и экраном 90 Гц для видео и чтения.',
       Chipset='Snapdragon 695', RAM='4GB', Storage='64GB', Screen='11 inch 90Hz'),
    _p('tablets', 'Xiaomi', 'Pad 6', 29900,
       '11-inch 144Hz display, Snapdragon 870 and an aluminium unibody with quad Dolby speakers.',
       'Дисплей 11 дюймов 144 Гц, Snapdragon 870 и цельный алюминиевый корпус с четырьмя динамиками Dolby.',
       Chipset='Snapdragon 870', RAM='8GB', Storage='256GB', Screen='11 inch 144Hz'),
    _p('tablets', 'Lenovo', 'Tab P12', 32900,
       'Large 12.7-inch 3K display with JBL speakers and a stylus in the box for notes and sketching.',
       'Большой 12,7-дюймовый 3K-дисплей, динамики JBL и стилус в комплекте для заметок и рисования.',
       Chipset='Dimensity 7050', RAM='8GB', Storage='128GB', Screen='12.7 inch 3K'),

    # ---- Headphones -------------------------------------------------------
    _p('headphones', 'Apple', 'AirPods Pro 2', 24900,
       'Active noise cancellation, Adaptive Audio and a USB-C MagSafe case with up to 30 hours total.',
       'Активное шумоподавление, Adaptive Audio и кейс MagSafe с USB-C — до 30 часов работы.',
       Type='In-ear TWS', ANC='Yes', Battery='6h + 24h case', Rating='IP54'),
    _p('headphones', 'Apple', 'AirPods Max', 54900,
       'Over-ear headphones with computational audio, ANC and a knit-mesh canopy for all-day comfort.',
       'Полноразмерные наушники с вычислительным звуком, ANC и сетчатым оголовьем для комфорта весь день.',
       Type='Over-ear', ANC='Yes', Battery='20h', Connectivity='Bluetooth 5.0'),
    _p('headphones', 'Sony', 'WH-1000XM5', 34900,
       'Industry-leading noise cancellation with eight microphones and 30 hours of battery.',
       'Лучшее в классе шумоподавление с восемью микрофонами и 30 часов автономности.',
       Type='Over-ear', ANC='Yes', Battery='30h', Connectivity='Bluetooth 5.2 multipoint'),
    _p('headphones', 'Sony', 'WF-1000XM5', 24900,
       'Compact earbuds with the best-in-class ANC, LDAC hi-res audio and 24 hours with the case.',
       'Компактные наушники с лучшим ANC, hi-res звуком LDAC и 24 часами работы с кейсом.',
       Type='In-ear TWS', ANC='Yes', Battery='8h + 16h case', Codec='LDAC'),
    _p('headphones', 'Samsung', 'Galaxy Buds3 Pro', 19900,
       'Blade-design earbuds with adaptive ANC, 24-bit hi-fi audio and real-time interpreter.',
       'Наушники дизайна Blade с адаптивным ANC, 24-битным hi-fi звуком и переводчиком в реальном времени.',
       Type='In-ear TWS', ANC='Yes', Battery='7h + 23h case', Rating='IP57'),
    _p('headphones', 'JBL', 'Tune 770NC', 9900,
       'Wireless over-ear with adaptive noise cancelling and a massive 70-hour battery.',
       'Беспроводные полноразмерные наушники с адаптивным шумоподавлением и батареей на 70 часов.',
       Type='Over-ear', ANC='Yes', Battery='70h', Connectivity='Bluetooth 5.3'),
    _p('headphones', 'Marshall', 'Major IV', 14900,
       'Iconic on-ear design, 80+ hours of wireless playtime and wireless charging.',
       'Культовый накладной дизайн, более 80 часов беспроводной работы и беспроводная зарядка.',
       Type='On-ear', ANC='No', Battery='80h', Driver='40mm'),
    _p('headphones', 'Xiaomi', 'Redmi Buds 5', 3900,
       'Budget earbuds with 46dB ANC, 12.4mm drivers and 38 hours total with the case.',
       'Бюджетные наушники с ANC 46 дБ, динамиками 12,4 мм и 38 часами работы с кейсом.',
       Type='In-ear TWS', ANC='Yes', Battery='10h + 28h case', Connectivity='Bluetooth 5.3'),

    # ---- Smartwatches -----------------------------------------------------
    _p('watches', 'Apple', 'Watch Series 10', 44900,
       'Thinnest Apple Watch with the biggest display, wide-angle OLED and sleep apnea notifications.',
       'Самые тонкие Apple Watch с самым большим дисплеем, широкоугольным OLED и уведомлениями об апноэ сна.',
       Size='46mm', Display='Always-On Retina', Sensors='ECG, SpO2, temperature', Water='50m'),
    _p('watches', 'Apple', 'Watch SE 2', 24900,
       'Essential Apple Watch features — activity rings, crash detection and heart notifications.',
       'Базовые функции Apple Watch: кольца активности, обнаружение аварий и уведомления о пульсе.',
       Size='44mm', Display='Retina', Connectivity='GPS', Water='50m'),
    _p('watches', 'Samsung', 'Galaxy Watch7', 29900,
       'Wear OS watch with a BIA body-composition sensor, sleep coaching and 40-hour battery.',
       'Часы на Wear OS с датчиком состава тела BIA, тренером сна и батареей на 40 часов.',
       Size='44mm', Display='Super AMOLED', OS='Wear OS 5', Battery='40h'),
    _p('watches', 'Xiaomi', 'Watch 2 Pro', 22900,
       'Stainless-steel Wear OS watch with a 1.43-inch AMOLED, dual-band GPS and 65 hours of battery.',
       'Часы из нержавеющей стали на Wear OS с AMOLED 1,43 дюйма, двухдиапазонным GPS и 65 часами работы.',
       Size='46mm', Display='1.43 inch AMOLED', OS='Wear OS', Battery='65h'),
    _p('watches', 'Huawei', 'Watch GT 5', 21900,
       'Two-week battery, TruSense health tracking and a lightweight polymer-fibre case.',
       'Две недели работы, отслеживание здоровья TruSense и лёгкий корпус из полимерного волокна.',
       Size='46mm', Display='1.43 inch AMOLED', Battery='14 days', Connectivity='GPS'),
    _p('watches', 'Garmin', 'Forerunner 265', 42900,
       'Running watch with an AMOLED display, multi-band GPS, training readiness and 13-day battery.',
       'Беговые часы с AMOLED-дисплеем, многодиапазонным GPS, готовностью к тренировке и батареей на 13 дней.',
       Size='46mm', Display='1.3 inch AMOLED', Connectivity='Multi-band GPS', Battery='13 days'),
    _p('watches', 'Amazfit', 'GTR 4', 15900,
       'Classic round design with dual-band GPS, 150+ sport modes and 14 days on a charge.',
       'Классический круглый дизайн с двухдиапазонным GPS, 150+ спортивными режимами и 14 днями работы.',
       Size='46mm', Display='1.43 inch AMOLED', Battery='14 days', Sports='150+ modes'),

    # ---- Monitors ---------------------------------------------------------
    _p('monitors', 'Samsung', 'Odyssey G5 32', 29900,
       '32-inch curved QHD gaming monitor with 165Hz, 1ms and FreeSync Premium.',
       '32-дюймовый изогнутый игровой монитор QHD с 165 Гц, 1 мс и FreeSync Premium.',
       Size='32 inch', Resolution='2560x1440', Refresh='165Hz', Panel='Curved VA'),
    _p('monitors', 'LG', 'UltraGear 27GP850', 34900,
       'Nano IPS 27-inch QHD with 165Hz (180Hz OC), 1ms GtG and G-Sync compatibility.',
       'Nano IPS 27 дюймов QHD с 165 Гц (180 Гц в разгоне), 1 мс GtG и поддержкой G-Sync.',
       Size='27 inch', Resolution='2560x1440', Refresh='165Hz', Panel='Nano IPS'),
    _p('monitors', 'Dell', 'S2722QC', 32900,
       '27-inch 4K IPS with USB-C 65W power delivery, built-in speakers and a height-adjustable stand.',
       '27-дюймовый 4K IPS с USB-C 65 Вт, встроенными динамиками и регулируемой по высоте подставкой.',
       Size='27 inch', Resolution='3840x2160', Refresh='60Hz', Ports='USB-C 65W, 2x HDMI'),
    _p('monitors', 'ASUS', 'ProArt PA278CV', 36900,
       'Colour-accurate 27-inch QHD for creators: 100% sRGB, Calman verified, USB-C hub.',
       'Точный по цвету 27-дюймовый QHD для дизайнеров: 100% sRGB, сертификация Calman, USB-C хаб.',
       Size='27 inch', Resolution='2560x1440', Colour='100% sRGB', Ports='USB-C 65W'),
    _p('monitors', 'AOC', '24G2', 14900,
       'Best-value 24-inch 144Hz IPS gaming monitor with 1ms MPRT and a frameless design.',
       'Лучший по цене 24-дюймовый игровой IPS-монитор 144 Гц с 1 мс MPRT и безрамочным дизайном.',
       Size='24 inch', Resolution='1920x1080', Refresh='144Hz', Panel='IPS'),
    _p('monitors', 'Xiaomi', 'Monitor A24i', 8900,
       'Slim 23.8-inch FHD IPS office monitor with 100Hz and low blue light mode.',
       'Тонкий офисный монитор 23,8 дюйма FHD IPS с 100 Гц и режимом защиты зрения.',
       Size='23.8 inch', Resolution='1920x1080', Refresh='100Hz', Panel='IPS'),
    _p('monitors', 'LG', '34WP65C', 39900,
       '34-inch curved ultrawide QHD with 160Hz, HDR10 and built-in speakers for work and play.',
       '34-дюймовый изогнутый ультраширокий QHD с 160 Гц, HDR10 и встроенными динамиками.',
       Size='34 inch', Resolution='3440x1440', Refresh='160Hz', Panel='Curved VA'),

    # ---- Speakers ---------------------------------------------------------
    _p('speakers', 'JBL', 'Flip 6', 11900,
       'Portable IP67 speaker with a racetrack woofer, separate tweeter and 12 hours of playtime.',
       'Портативная колонка IP67 с овальным вуфером, отдельным твитером и 12 часами работы.',
       Power='30W', Battery='12h', Rating='IP67', Connectivity='Bluetooth 5.1'),
    _p('speakers', 'JBL', 'Charge 5', 15900,
       'Bigger sound, 20 hours of battery and a built-in powerbank to charge your phone.',
       'Более мощный звук, 20 часов работы и встроенный powerbank для зарядки телефона.',
       Power='40W', Battery='20h', Rating='IP67', Extra='Powerbank USB-A'),
    _p('speakers', 'Marshall', 'Emberton II', 16900,
       'Iconic Marshall look with 360° True Stereophonic sound and 30+ hours of playtime.',
       'Культовый дизайн Marshall с 360° True Stereophonic звуком и более 30 часами работы.',
       Power='20W', Battery='30h', Rating='IP67', Connectivity='Bluetooth 5.1'),
    _p('speakers', 'Sony', 'SRS-XB100', 5900,
       'Pocket-size speaker with Extra Bass, IP67 protection and 16 hours of battery.',
       'Карманная колонка с Extra Bass, защитой IP67 и 16 часами автономности.',
       Battery='16h', Rating='IP67', Connectivity='Bluetooth 5.3', Weight='274g'),
    _p('speakers', 'Bose', 'SoundLink Flex', 14900,
       'PositionIQ technology adapts the sound to how it sits; floats, and shrugs off dust and water.',
       'Технология PositionIQ подстраивает звук под положение колонки; не тонет, не боится пыли и воды.',
       Battery='12h', Rating='IP67', Connectivity='Bluetooth 4.2', Weight='600g'),
    _p('speakers', 'Xiaomi', 'Mi Portable Speaker 16W', 3900,
       'Stereo-pairable 16W speaker with IPX7 waterproofing and 13 hours of battery.',
       'Колонка 16 Вт с возможностью стереопары, защитой IPX7 и 13 часами работы.',
       Power='16W', Battery='13h', Rating='IPX7', Connectivity='Bluetooth 5.0'),

    # ---- Accessories ------------------------------------------------------
    _p('accessories', 'Apple', '20W USB-C Power Adapter', 2400,
       'Fast-charge an iPhone to 50% in around 30 minutes with the official 20W adapter.',
       'Быстрая зарядка iPhone до 50% примерно за 30 минут официальным адаптером 20 Вт.',
       shape='charger', Power='20W', Port='USB-C', Compatibility='iPhone, iPad, AirPods'),
    _p('accessories', 'Apple', 'MagSafe Charger', 4400,
       'Magnetic wireless charging up to 25W for iPhone 12 and later, with a 1m USB-C cable.',
       'Магнитная беспроводная зарядка до 25 Вт для iPhone 12 и новее, кабель USB-C 1 м.',
       shape='puck', Power='25W', Type='Wireless MagSafe', Cable='1m USB-C'),
    _p('accessories', 'Anker', 'PowerCore 20000', 4900,
       '20,000mAh powerbank with 22.5W fast charging and two USB-C ports.',
       'Powerbank 20 000 мАч с быстрой зарядкой 22,5 Вт и двумя портами USB-C.',
       shape='powerbank', Capacity='20000mAh', Power='22.5W', Ports='2x USB-C, 1x USB-A'),
    _p('accessories', 'Xiaomi', '33W Power Bank 10000', 2600,
       'Slim 10,000mAh powerbank that can also charge laptops and tablets at 33W.',
       'Тонкий powerbank 10 000 мАч, заряжает ноутбуки и планшеты мощностью 33 Вт.',
       shape='powerbank', Capacity='10000mAh', Power='33W', Ports='1x USB-C, 1x USB-A'),
    _p('accessories', 'Baseus', '65W GaN Charger', 3400,
       'Three-port GaN charger that powers a laptop, phone and earbuds at once.',
       'Трёхпортовое зарядное устройство GaN: ноутбук, телефон и наушники одновременно.',
       shape='charger', Power='65W', Ports='2x USB-C, 1x USB-A', Technology='GaN'),
    _p('accessories', 'Samsung', '45W Super Fast Charger', 2900,
       'Official 45W USB-C charger for Galaxy S and Tab with the 1.8m cable included.',
       'Официальное зарядное USB-C 45 Вт для Galaxy S и Tab с кабелем 1,8 м в комплекте.',
       shape='charger', Power='45W', Port='USB-C', Cable='1.8m USB-C included'),
    _p('accessories', 'Logitech', 'MX Master 3S', 10900,
       'Quiet-click productivity mouse with an 8000 DPI sensor, MagSpeed scroll wheel and 70-day battery.',
       'Тихая мышь для работы с сенсором 8000 DPI, колесом MagSpeed и батареей на 70 дней.',
       shape='mouse', Sensor='8000 DPI', Battery='70 days', Connectivity='Bluetooth, Logi Bolt'),
    _p('accessories', 'Logitech', 'MX Keys Mini', 9900,
       'Compact wireless keyboard with smart backlighting and pairing for three devices.',
       'Компактная беспроводная клавиатура с умной подсветкой и подключением к трём устройствам.',
       shape='keyboard', Layout='Compact', Backlight='Smart', Connectivity='Bluetooth, Logi Bolt'),
    _p('accessories', 'SanDisk', 'Extreme Portable SSD 1TB', 10900,
       'Rugged IP65 portable SSD with 1050MB/s reads for photos, video and backups.',
       'Защищённый портативный SSD IP65 со скоростью чтения 1050 МБ/с для фото, видео и бэкапов.',
       shape='drive', Capacity='1TB', Speed='1050MB/s', Rating='IP65', Port='USB-C 3.2'),
    _p('accessories', 'Ugreen', 'USB-C Hub 7-in-1', 3900,
       'Adds HDMI 4K, three USB-A, SD/microSD and 100W pass-through charging to any USB-C laptop.',
       'Добавляет HDMI 4K, три USB-A, SD/microSD и сквозную зарядку 100 Вт любому ноутбуку с USB-C.',
       shape='hub', Ports='HDMI 4K, 3x USB-A, SD, microSD', Power='100W pass-through'),
]
